format = """
[â”‚](bold green) $username@$hostname in ğŸ“‚ $directory$git_branch
[â””â”€>](bold green) """

[username]
style_user = "bold purple"
style_root = "bold red"
format = "ğŸ‘¤ [$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold yellow)"
disabled = false

[git_branch]
symbol = "ğŸ—ï¸  "
truncation_length = 4
truncation_symbol = ""